# roles/webserver/tasks/main.yml
---
- name: 1. install Apache
  yum: name=httpd state=present

- name: 2. install PHP module for Apache
  yum: name=php-fpm state=present

- name: 3. start Apache
  service: name=httpdstate=running enabled=yes

- name: 4. install Hello World PHP script
  copy: src=index.php dest=/var/www/html/index.php mode=0664

- user: name=otemmo comment="My User" group=wheel

- name: Placing key
  authorized_key: user=otemmo key="{{ lookup('file', './files/id_otemmo.pub') }}"
